### ISSUE TITLE
win long paths problem with gitpython?

### ISSUE THREAD

**Issue by maybeec** [gitpython-developers/GitPython#1011]
I have --long-paths set to be true on win10 + latest git version, which works like a charm.
Anyhow, executing gitpython clone command, the cloning of a repository with extra long paths does not work out and throws 

```
Exception ignored in: <finalize object at 0x1da516aff90; dead>
Traceback (most recent call last):
  File "weakref.py", line 566, in __call__
  File "tempfile.py", line 818, in _cleanup
  File "tempfile.py", line 814, in _rmtree
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 610, in _rmtree_unsafe
  File "shutil.py", line 610, in _rmtree_unsafe
  File "shutil.py", line 610, in _rmtree_unsafe
  [Previous line repeated 15 more times]
  File "shutil.py", line 619, in _rmtree_unsafe
  File "shutil.py", line 617, in _rmtree_unsafe
OSError: [WinError 145] The directory is not empty <long path here>:
```

does gitpython have an issue with long paths?

**Comment by maybeec** [comment]
ok, seems, that it was a problem with tempfile... closing this again.
