### ISSUE TITLE
Failing to parse header on simple example

### ISSUE THREAD

**Issue by robambalu** [gitpython-developers/GitPython#1029]
I just installed gitpython and on my very first attempt I'm hitting strange errors.
Simple example, NYC corona virus github:
git clone https://github.com/nychealth/coronavirus-data

in python, create repo:
>>> r = Repo( 'coronavirus-data')

lets get the latest commit date ( poof )

>>> r.head.commit.committed_date
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\gitdb\util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\git\objects\commit.py", line 142, in _set_cache_
    _binsha, _typename, self.size, stream = self.repo.odb.stream(self.binsha)
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\git\db.py", line 42, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(sha))
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\git\cmd.py", line 1085, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\git\cmd.py", line 1057, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "C:\Users\robam\AppData\Local\Programs\Python\Python38\lib\site-packages\git\cmd.py", line 1021, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'10004,Financial' could not be resolved, git returned: b'10004,Financial District,Manhattan,33,903.96,3650.61,1,27.39,6.75,489'

**Comment by robambalu** [comment]
FYI this seems to be a problem when running from an interactive shell, running within a script seems to work ok

**Comment by Byron** [comment]
I believe this is a shortcoming when there are multiple handles to objects at the same time. Depending on the order of operations, they may interfere with each other. Due to long-lived objects in an interactive shell, this issue may be more prominent than in scripts, where one more naturally works with one object at a time.

The only way to workaround this is to create a repository with a [non-default object database implementation](https://gitpython.readthedocs.io/en/stable/tutorial.html#gitdb).

In the hopes that this helps, I am closing the issue on the grounds of it being know and that a fix is not possible, but a workaround. Please let me know if you think this is something else, or if the workaround doesn't seem effective.
