### ISSUE TITLE
Cannot retrieve the old content from a diff

### ISSUE THREAD

**Issue by simisimon** [gitpython-developers/GitPython#1094]
GitPython is failing to retrieve the old content from a diff  for specific repositories I am currently analyzing:

 ``https://github.com/d3/d3``
`` https://github.com/bumptech/glide``

There are also other repositories that are affected, but I think these are enough to describe the problem.

Here is the exception's stack trace:

```
Traceback (most recent call last):
  File "D:\Projects\gitpython-issue\main.py", line 33, in repo_problem
    content_old = diff.a_blob.data_stream.read().decode("latin-1")
  File "D:\Projects\gitpython-issue\venv\lib\site-packages\git\objects\base.py", line 112, in data_stream
    return self.repo.odb.stream(self.binsha)
  File "D:\Projects\gitpython-issue\venv\lib\site-packages\git\db.py", line 42, in stream
    hexsha, typename, size, stream = self._git.stream_object_data(bin_to_hex(sha))
  File "D:\Projects\gitpython-issue\venv\lib\site-packages\git\cmd.py", line 1085, in stream_object_data
    hexsha, typename, size = self.__get_object_header(cmd, ref)
  File "D:\Projects\gitpython-issue\venv\lib\site-packages\git\cmd.py", line 1057, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "D:\Projects\gitpython-issue\venv\lib\site-packages\git\cmd.py", line 1021, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'b6575ef0b658ab77d2247a88b995c2c623e9d6a7' could not be resolved, git returned: b'b6575ef0b658ab77d2247a88b995c2c623e9d6a7 missing'
```

Reproducible example:

`` $ git clone https://github.com/d3/d3.git``

```python
    d3 = path.abspath("D:\GitHub\d3")
    repo = Repo(d3)
    commit_history = list(repo.iter_commits(rev=repo.heads[0]))
    commit_history.reverse()

    for i in range(0, len(commit_history)):
        current_commit = commit_history[i]
        next_commit = commit_history[i+1]
        print("Commit: ", current_commit.hexsha)

        diff_index = current_commit.diff(next_commit, create_patch=False)

        change_types = {"M", "R", "T"}

        for diff in diff_index:
            if diff.change_type in change_types:
                content_old = diff.a_blob.data_stream.read().decode("latin-1")
                content_new = diff.b_blob.data_stream.read().decode("latin-1")
```

I checked, if the corresponding commit is part of the repository with ``git show``:

````
D:\GitHub\d3>git show b6575ef0b658ab77d2247a88b995c2c623e9d6a7
fatal: bad object b6575ef0b658ab77d2247a88b995c2c623e9d6a7
````

I am not quite sure how this is possible. So I would appreciate any help with this problem.

**Comment by Byron** [comment]
I took a look using the following script:

```python
import os
import git

import logging
logging.basicConfig(level=logging.INFO)

d3 = os.path.abspath("d3")
repo = git.Repo(d3)
commit_history = list(repo.iter_commits(rev=repo.heads[0]))
commit_history.reverse()

for i in range(0, len(commit_history)):
    current_commit = commit_history[i]
    next_commit = commit_history[i+1]
    print("Commit: ", current_commit.hexsha)

    diff_index = current_commit.diff(next_commit, create_patch=False)

    change_types = {"M", "R", "T"}

    for diff in diff_index:
        if diff.change_type in change_types:
            content_old = diff.a_blob.data_stream.read().decode("latin-1")
            content_new = diff.b_blob.data_stream.read().decode("latin-1")
```

…which was executed with `GIT_PYTHON_TRACE=full python3 ./test.py` once the repository was cloned.

This showed that `git diff-tree` is executed on a particular commit which produces the object hash that doesn't exist:

```
git diff-tree 7c2062f2895376e823a4c0ac04671297d734fe99 00d8bf71a3a0851d07eb7d7a437108a8e73b9e34 -r --abbrev=40 --full-index -M --raw --no-color
:100644 100644 316eee329308fad43adaccd2b4202c776b5daee8 fbc9472b6c6f07b49e44fb4a722bcdd3cf206944 M      .gitmodules
:100644 100644 be3ccf5011a384e70f4eaa238f00aadf1b0a6a8e cc04725c1e195816dc9a4775968f4e41a59c8bdf M      Makefile
:160000 160000 b6575ef0b658ab77d2247a88b995c2c623e9d6a7 b6575ef0b658ab77d2247a88b995c2c623e9d6a7 R100   lib/uglifyjs    lib/uglify-js
```

The reason seems to be incorrect handling of submodules, as indicated by the `1600000` file mode of `lig/uglify-js`. This submodule has since been removed.

Probably it would be best for the code above to ignore submodule changes alltogether, like so:

```python
import os
import git

import logging
logging.basicConfig(level=logging.INFO)

d3 = os.path.abspath("d3")
repo = git.Repo(d3)
commit_history = list(repo.iter_commits(rev=repo.heads[0]))
commit_history.reverse()

for i in range(0, len(commit_history)):
    current_commit = commit_history[i]
    next_commit = commit_history[i+1]
    print("Commit: ", current_commit.hexsha)

    diff_index = current_commit.diff(next_commit, create_patch=False)

    change_types = {"M", "R", "T"}

    for diff in diff_index:
        if diff.change_type in change_types:
            if diff.a_mode == 0o160000 or diff.b_mode == 0o160000:
                print("skipped submodule at ", diff.a_path)
                continue
            content_old = diff.a_blob.data_stream.read().decode("latin-1")
            content_new = diff.b_blob.data_stream.read().decode("latin-1")
```

The one above can handle the entire history, despite not handling the first commit properly which doesn't have a parent.

**Comment by simisimon** [comment]
Thank you for your quick reply. I will definitely try your solution.
