### ISSUE TITLE
`import git` fails when current working directory is not accessible

### ISSUE THREAD

**Issue by comzyh** [gitpython-developers/GitPython#1334]
Very similar to #1319
Steps to reproduce:

```shell
$ mkdir /tmp/foo
$ cd /tmp/foo
$ chmod -x .
$ python -c "import git"
```

Crash with:

```
Traceback (most recent call last):
  File "/home/comzyh/.local/lib/python3.8/site-packages/git/__init__.py", line 87, in <module>
    refresh()
  File "/home/comzyh/.local/lib/python3.8/site-packages/git/__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "/home/comzyh/.local/lib/python3.8/site-packages/git/cmd.py", line 305, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/comzyh/.local/lib/python3.8/site-packages/git/__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

GitPython: 3.1.20

GitPython will run a `git version`  when importing, but if the current workding dir is not accessible, the Popen clause will fail.

https://github.com/gitpython-developers/GitPython/blob/ef1ef4db2553384cc615ca2c5836883c52b910b0/git/cmd.py#L821

This can be fixed by adding 2 lines after https://github.com/gitpython-developers/GitPython/commit/5b3669e24a8ce7f3f482de86fcf95620db643467, but I'm not sure if this fix will break some of your assumption.
```python
        # Allow the user to have the command executed in their working dir.
        try:
            cwd = self._working_dir or os.getcwd()  # type: Union[None, str]            
        except FileNotFoundError:
            cwd = None
        if not os.access(cwd, os.X_OK):
            cwd = None
```

I found this issue when I'm a previliedged user and try to switch user using `sudo su <user>` and then run a Python script which need a package depending on GitPython.

**Comment by Byron** [comment]
Thanks a lot, I have added the additional check assuming this fixes the issue described here.
