### ISSUE TITLE
submodules without commits

### ISSUE THREAD

**Issue by cancerhermit** [gitpython-developers/GitPython#152]
Traceback (most recent call last):
  File "GitPython.python.examples/_Examples/git submodule/test.py", line 7, in <module>
    print repo.submodules
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 238, in submodules
    return Submodule.list_items(self)
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/util.py", line 659, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/submodule/base.py", line 883, in iter_items
    pc = repo.commit(parent_commit)			# parent commit instance
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/base.py", line 378, in commit
    return self.rev_parse(str(rev)+"^0")
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/fun.py", line 151, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/Library/Python/2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/repo/fun.py", line 86, in name_to_object
    raise BadObject(name)
gitdb.exc.BadObject: BadObject: 48454144
[Finished in 6.8s with exit code 1]

**Comment by Byron** [comment]
Just for completeness: This would now throw `BadName`, see #105 for more information.
Nonetheless, I am looking into this right now to see what the desired behaviour should be.

**Comment by Byron** [comment]
Please have a look at the commit message above for a summary on why this is considered fixed. In short, I believe that adding empty submodules is wrong in the first place, and doesn't seem to be possible either with the git-commandline, nor with git-python.

You can watch the archived live-development video [on youtube](http://youtu.be/YeuKMlUgBh8)
