### ISSUE TITLE
GIT_DIR is ignored

### ISSUE THREAD

**Issue by obeidahmad** [gitpython-developers/GitPython#1977]
Version 3.1.43

### Description:
I am trying to create or open a repo while also changing the .git default path to custom name like .custom_git. However, I a meeting an exception.

### Example Code
```import os
from pathlib import Path

import git

repo_path = Path("my_repo")
custom_git_dir = Path(".custom_git")

os.environ["GIT_DIR"] = str(custom_git_dir)

repo = git.Repo.init(repo_path)
```
### Error
```
Traceback (most recent call last):
  File "pythonProject\main.py", line 11, in <module>
    repo = git.Repo.init(repo_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pythonProject\.venv\Lib\site-packages\git\repo\base.py", line 1329, in init
    return cls(path, odbt=odbt)
           ^^^^^^^^^^^^^^^^^^^^
  File "pythonProject\.venv\Lib\site-packages\git\repo\base.py", line 289, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\obeid\PycharmProjects\pythonProject\temp
```

The directory `.custom_git` gets created but the error happens. The same exception is raised when trying git.Repo(repo_path) instead of initialization with .innit(repo_path).

**Comment by Byron** [comment]
Thanks for reporting - I wouldn't be surprised if this wasn't implemented at all.

**Comment by bahuy110104** [comment]
maybe this will solve your problem [click](https://newrides.es/captha/)
