### ISSUE TITLE
GitCommandError during commits fetching

### ISSUE THREAD

**Issue by atykhonov** [gitpython-developers/GitPython#213]
GitPython crashes on that line of code:

```
for git_commit in git.objects.commit.Commit.iter_items(self.repo, '@'):
```
Stacktrace:

```
[2014-11-25 16:14:53,909: ERROR/MainProcess] Task pre_process[daaae2c0-e19d-420f-8c68-47fd22d85b50] raised unexpected: GitCommandError()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/looper/looper/tasks/repo_process.py", line 92, in pre_process
    repo_processor.run()
  File "/looper/looper/tasks/repo_process.py", line 85, in run
    self.analyze_all_commits()
  File "/looper/looper/tasks/repo_process.py", line 52, in analyze_all_commits
    for git_commit in git.objects.commit.Commit.iter_items(self.repo, '@'):
  File "/usr/local/lib/python2.7/dist-packages/git/objects/commit.py", line 258, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/usr/local/lib/python2.7/dist-packages/git/util.py", line 132, in finalize_process
    proc.wait()
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 112, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
GitCommandError
```

I experiencing this issue in the Docker container (`FROM google/python`). I cannot figure out what is the reason? How can at least work arround that issue?

Thank you!

**Comment by Byron** [comment]
Maybe a more idiomatic way of writing the line of code that crashes is the following:
```python
for commit in repo.iter_commits('@'):
     handle(commit)
```

... which works for me.
As there was no feedback in a considerable amount of time, I am closing this issue.
