### ISSUE TITLE
Pypy2.4.0 support

### ISSUE THREAD

**Issue by andrefreitas** [gitpython-developers/GitPython#267]
Hi,
I am trying to use gitpython in pypy2.4.0 but I got an exception:

````
>>>> import git
>>>> git.Repo("/Users/andre/git/MPAndroidChart")
<git.Repo "/Users/andre/git/MPAndroidChart/.git">
>>>> r = git.Repo("/Users/andre/git/MPAndroidChart")
>>>> r.iter_commits(max_count=6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/pypy3-2.4.0-osx64/site-packages/git/repo/base.py", line 466, in iter_commits
    rev = self.head.commit
  File "/Applications/pypy3-2.4.0-osx64/site-packages/git/refs/symbolic.py", line 182, in _get_commit
    obj = self._get_object()
  File "/Applications/pypy3-2.4.0-osx64/site-packages/git/refs/symbolic.py", line 175, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
TypeError: 'str' does not support the buffer interface
```
I am getting this in any repository.

**Comment by Byron** [comment]
Thanks for posting.
However, pypy is not supported.
If you have seen this stated somewhere, please let me know and I will try to fix that.
