### ISSUE TITLE
gitconfig parser fails to parse config keys without values

### ISSUE THREAD

**Issue by auscompgeek** [gitpython-developers/GitPython#352]
Here is a snippet of my `~/.config/git/config`:
```ini
[diff]
	mnemonicPrefix
[rebase]
	stat
[merge]
	summary
	tool = vimdiff
```

GitPython raises a `configparser.ParsingError` for the lines without values:
```pytb
Traceback (most recent call last):
  ...
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/refs/head.py", line 162, in tracking_branch
    if reader.has_option(self.k_config_remote) and reader.has_option(self.k_config_remote_ref):
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/config.py", line 114, in <lambda>
    return lambda *args, **kwargs: self._call_config(attr, *args, **kwargs)
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/config.py", line 120, in _call_config
    return getattr(self._config, method)(self._section_name, *args, **kwargs)
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/config.py", line 70, in assure_data_present
    self.read()
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/config.py", line 378, in read
    self._read(fp, fp.name)
  File "/home/auscompgeek/.local/lib/python3.4/site-packages/git/config.py", line 340, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/auscompgeek/.config/git/config'
	[line 28]: '\tmnemonicPrefix\n'
	[line 30]: '\tstat\n'
	[line 32]: '\tsummary\n'
```

**Comment by auscompgeek** [comment]
Gah, I just noticed #349. Figures.

**Comment by cyphar** [comment]
#349 doesn't fix it, it still requires values. BTW, this regex is **incredibly** difficult to read:

```
    optvalueonly_source = r'\s*(?P<option>[^:=\s][^:=]*)'

    OPTVALUEONLY = re.compile(optvalueonly_source)

    OPTCRE = re.compile(
        optvalueonly_source                          # very permissive, incuding leading whitespace
        + r'\s*(?P<vi>[:=])\s*'               # any number of space/tab,
                                              # followed by separator
                                              # (either : or =), followed
                                              # by any # space/tab
        + r'(?P<value>.*)$'                     # everything up to eol
    )
```
