### ISSUE TITLE
Git Review ParsingErrors

### ISSUE THREAD

**Issue by dulith** [gitpython-developers/GitPython#359]
```bash
MACs-MacBook-Pro:phoenix-ui BOOK$  git review -s
Using global/system git-review config files (/Users/BOOK/.config/git-review/git-review.conf) is deprecated
Traceback (most recent call last):
  File "/usr/local/bin/git-review", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 1522, in main
    _main()
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 1393, in _main
    config = Config(os.path.join(top_dir, ".gitreview"))
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 285, in __init__
    self.config.update(load_config_file(filename))
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 671, in load_config_file
    configParser.read(config_file)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /Users/BOOK/.config/git-review/git-review.conf
	[line  2]: '\tdefaultremote = origin\n'
	[line  3]: '\tdefaultbranch = develop\n'
MACs-MacBook-Pro:phoenix-ui BOOK$ git config --global --add gitreview.username "dpathirage@rivermeadow.com"
MACs-MacBook-Pro:phoenix-ui BOOK$  git review -s
Using global/system git-review config files (/Users/BOOK/.config/git-review/git-review.conf) is deprecated
Traceback (most recent call last):
  File "/usr/local/bin/git-review", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 1522, in main
    _main()
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 1393, in _main
    config = Config(os.path.join(top_dir, ".gitreview"))
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 285, in __init__
    self.config.update(load_config_file(filename))
  File "/usr/local/lib/python2.7/site-packages/git_review/cmd.py", line 671, in load_config_file
    configParser.read(config_file)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /Users/BOOK/.config/git-review/git-review.conf
	[line  2]: '\tdefaultremote = origin\n'
	[line  3]: '\tdefaultbranch = develop\n'
```

**Comment by Byron** [comment]
Which version of GitPython are you using ? If it is not the latest from GitHub, please try to reproduce the error with the version from this repository - it has received plenty of fixes since the last release on PyPi (v1.0.1).
If the error persists, please post additional information to help me reproduce the issue - I'd think sharing the entire content of `/Users/BOOK/.config/git-review/git-review.conf` would help.
Thank you

**Comment by dulith** [comment]
Hi Bryon, I got the Issue fixed. It was not associated with the Pyton it was an issue with git-rview.cofig file. Thanks for your response.

**Comment by cxw42** [comment]
For anyone else finding this issue from Google, my problem was the leading whitespace on my key-value lines.  For example,

     [section]
      k=v   
     ↑
     └ Note leading space!

produces a ParsingError, but

    [section]
    k=v   
    ↑
    └  _without_ leading space

parses fine.  I think this may be related to line-continuation support, but I am not sure.
