### ISSUE TITLE
Windows 8.1 GitCommandNotFound: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by FlYnN91** [gitpython-developers/GitPython#370]
Hi,

I've been notified with this error and I cannot seem to resolve.

r =  git.Repo.init(workingDir)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\repo\base.py", line 764, in init
    git.init(**kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 810, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
GitCommandNotFound: [Error 2] The system cannot find the file specified

I have git in my Environment path.

**Comment by Byron** [comment]
It seems by default GitPython doesn't use a shell anymore, which could imply that on windows it will not look up the `git` executable in the `PATH` anymore. Interestingly, this still works on unix-like operating systems.

However, you can always be explicit about the git executable to invoke, by using the `GIT_PYTHON_GIT_EXECUTABLE` environment variable. Just set it to the full path to the git executable on your system.

Please note that it is highly recommended to use the latest version from this repository, as it contains many, sometimes critical fixes.

I hope that helped.

**Comment by FlYnN91** [comment]
Hi,

Thank you for the advice. I've added the env variable as suggested and it fixed the initial error but raised a new one:

Traceback (most recent call last):
  File "C:\TestingQVCSMigration\migrateLabelToRepository.py", line 71, in <module>
    setupGitRepository(cloneUrl,workingDir)
  File "C:\TestingQVCSMigration\migrateLabelToRepository.py", line 51, in setupGitRepository
    r = git.Repo.init(workingDir)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\repo\base.py", line 764, in init
    git.init(**kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 810, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Python27\lib\site-packages\gitpython-1.0.1-py2.7.egg\git\cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
GitCommandNotFound: [Error 5] Access is denied

I'll just resort to calling subprocess.Popen for the time being.
