### ISSUE TITLE
Error while cloning a repo via Repo.clone_from

### ISSUE THREAD

**Issue by ChannyAzar** [gitpython-developers/GitPython#403]
I can't clone a repo from git via `Repo.clone_from`

```
~/Projects/development$ python
Python 2.7.9 (default, Mar  3 2016, 16:42:45) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from git import Repo
>>> Repo.clone_from("git@github.com:my_path.git" , "to_dest", "master")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 885, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 828, in _clone
    handle_process_output(proc, None, progress.new_message_handler(), finalize_process)
AttributeError: 'str' object has no attribute 'new_message_handler'
```

Python 2.7.9 
[GCC 4.6.3] on linux2
Git version '1.0.2'`

**Comment by Byron** [comment]
It seems as if a string is passed in the spot of the *message handler*. What happens if you call it like so: 
```python
 Repo.clone_from("git@github.com:my_path.git" , "to_dest", branch="master")
```

**Comment by ChannyAzar** [comment]
Thanks. It's working now.
