### ISSUE TITLE
Lots of tests errors on fresh new clone

### ISSUE THREAD

**Issue by peterbe** [gitpython-developers/GitPython#478]
I just did a clone, created a 3.5 virtualenv and installed the requirements and ran the (nose) tests. 

`FAILED (errors=11, failures=3)`

Either I'm doing something wrong with my set up or there's something missing from the README about how to run tests. 

By the way, I created a virtualenv for py 2.7 and also got `FAILED (errors=11, failures=3)`, 

```
(GitPython) :~/dev/PYTHON/GitPython (commit-without-executing-hooks)$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): gitdb>=0.6.4 in /Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): smmap>=0.8.5 in /Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages (from gitdb>=0.6.4->-r requirements.txt (line 1))
(GitPython) :~/dev/PYTHON/GitPython (commit-without-executing-hooks)$ pip install -r test-requirements.txt
Requirement already satisfied (use --upgrade to upgrade): gitdb>=0.6.4 in /Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Collecting coverage (from -r test-requirements.txt (line 3))
  Using cached coverage-4.1-cp35-cp35m-macosx_10_10_x86_64.whl
Collecting flake8 (from -r test-requirements.txt (line 4))
  Using cached flake8-2.6.0-py2.py3-none-any.whl
Collecting nose (from -r test-requirements.txt (line 5))
  Using cached nose-1.3.7-py3-none-any.whl
Collecting mock (from -r test-requirements.txt (line 6))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): smmap>=0.8.5 in /Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages (from gitdb>=0.6.4->-r requirements.txt (line 1))
Collecting mccabe<0.6,>=0.2.1 (from flake8->-r test-requirements.txt (line 4))
  Using cached mccabe-0.5.0-py2.py3-none-any.whl
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3,>=0.8.1 (from flake8->-r test-requirements.txt (line 4))
  Using cached pyflakes-1.2.3-py2.py3-none-any.whl
Collecting pycodestyle<2.1,>=2.0 (from flake8->-r test-requirements.txt (line 4))
  Using cached pycodestyle-2.0.0-py2.py3-none-any.whl
Collecting six>=1.9 (from mock->-r test-requirements.txt (line 6))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->-r test-requirements.txt (line 6))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Installing collected packages: coverage, mccabe, pyflakes, pycodestyle, flake8, nose, six, pbr, mock
Successfully installed coverage-4.1 flake8-2.6.0 mccabe-0.5.0 mock-2.0.0 nose-1.3.7 pbr-1.10.0 pycodestyle-2.0.0 pyflakes-1.2.3 six-1.10.0
(GitPython) :~/dev/PYTHON/GitPython (commit-without-executing-hooks)$ nosetests
Iterated 1474 Commits in 0.11196088790893555 [s] ( 13165.311811 commits/s )
.Serialized 2454 and deserialized 1227 commits in 0.899522 s ( (2728.115399, 1364.057699) commits / s
Serialized 5000 commits to loose objects in 1.337186 s ( 3739.195987 commits / s )
.Traversed 1473 Commits in 0.12391781806945801 [s] ( 11886.910397 commits/s )
.Traversed 161 Trees and a total of 11863 unchached objects in 0.4545879364013672 [s] ( 26096.161051 objs/s )
.<class 'git.db.GitCmdObjectDB'>: Retrieved 1473 commits from ObjectStore in 0.117784 s ( 12505.965925 commits / s )
<class 'git.db.GitCmdObjectDB'>: Retrieved 219201 objects from 1473 commits in 3.60269 s ( 60843.618656 objects / s )
<class 'git.db.GitCmdObjectDB'>: Retrieved 15050 blob (155793 KiB) and their data in 0.765244 s ( 19666.929581 blobs / s, 203586.058241 KiB / s )
<class 'gitdb.db.git.GitDB'>: Retrieved 1473 commits from ObjectStore in 0.150734 s ( 9772.184846 commits / s )
<class 'gitdb.db.git.GitDB'>: Retrieved 219201 objects from 1473 commits in 5.09656 s ( 43009.598620 objects / s )
<class 'gitdb.db.git.GitDB'>: Retrieved 15050 blob (155793 KiB) and their data in 3.02074 s ( 4982.218127 blobs / s, 51574.402889 KiB / s )
Iterate Commits: 0.117784 s vs 0.150734 s, pure is 1.279751 times slower
Iterate Blobs: 3.602695 s vs 5.096560 s, pure is 1.414652 times slower
Retrieve Blob Data: 0.765244 s vs 3.020743 s, pure is 3.947424 times slower
.Creating  data ...
Done (in 0.247781 s)
Added 10000 KiB (filesize = 3458 KiB) of  data to loose odb in 0.203285 s ( 49192.026168 Write KiB / s)
Read 10000 KiB of  data at once from loose odb in 0.051063 s ( 195836.282649 Read KiB / s)
Read 10000 KiB of  data in 512 KiB chunks from loose odb in 0.041844 s ( 238983.510535 Read KiB / s)
Added 10000 KiB (filesize = 3458 KiB) of  data to using git-hash-object in 0.211450 s ( 47292.481785 Write KiB / s)
Git-Python is 3.861488 % faster than git when adding big  files
Read 10000 KiB of  data at once using git-cat-file in 0.039203 s ( 255082.984145 Read KiB / s)
Git-Python is -30.253179 % faster than git when reading big files
Read 10000 KiB of  data in 512 KiB chunks from git-cat-file in 0.030484 s ( 328041.358058 Read KiB / s)
Git-Python is -37.265269 % faster than git when reading big  files in chunks
Creating random  data ...
Done (in 2.911585 s)
Added 10000 KiB (filesize = 8220 KiB) of random  data to loose odb in 0.327541 s ( 30530.518479 Write KiB / s)
Read 10000 KiB of random  data at once from loose odb in 0.081819 s ( 122221.270321 Read KiB / s)
Read 10000 KiB of random  data in 512 KiB chunks from loose odb in 0.069524 s ( 143835.119425 Read KiB / s)
Added 10000 KiB (filesize = 8220 KiB) of random  data to using git-hash-object in 0.366658 s ( 27273.356239 Write KiB / s)
Git-Python is 10.668545 % faster than git when adding big random  files
Read 10000 KiB of random  data at once using git-cat-file in 0.065641 s ( 152343.980415 Read KiB / s)
Git-Python is -24.646046 % faster than git when reading big random files
Read 10000 KiB of random  data in 512 KiB chunks from git-cat-file in 0.066502 s ( 150371.743347 Read KiB / s)
Git-Python is -4.544526 % faster than git when reading big random  files in chunks
........................................................Test Tutorials.test_init_repo_object failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_init_repo_objectidcuu4n9'
FTest Tutorials.test_references_and_objects failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_references_and_objectsbokyj9sk'
EE..............................................Keeping repos after failure: repo_dir = /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmpin72bh40remote_clone_non_bare_repo, remote_repo_dir = /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp3m8y8blrremote_repo_test_base
E......................................E..Keeping repo after failure: /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp2n_lzif5non_bare_test_submodule_update
EF.....Test TestRepo.test_work_tree_unsupported failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_work_tree_unsupportedm_48yarg'
E...Keeping repo after failure: /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp464ztadcnon_bare_test_base_rw
ETest TestSubmodule.test_branch_renames failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_branch_renamesevvj3iu1'
E.Test TestSubmodule.test_git_submodule_compatibility failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_git_submodule_compatibilitygjtnf1gw'
ETest TestSubmodule.test_git_submodules_and_add_sm_with_new_commit failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_git_submodules_and_add_sm_with_new_commitjypz0b2t'
ETest TestSubmodule.test_rename failed, output is at '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_renameyc_3jidj'
EKeeping repo after failure: /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp95t8udnwnon_bare_test_root_module
F.........
======================================================================
ERROR: test_references_and_objects (git.test.test_docs.Tutorials)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_docs.py", line 185, in test_references_and_objects
    repo = git.Repo.clone_from(self._small_repo_url(), os.path.join(rw_dir, 'repo'), branch='master')
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --branch=master -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_references_and_objectsbokyj9sk/repo' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist
'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_submodules (git.test.test_docs.Tutorials)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_docs.py", line 449, in test_submodules
    assert sm.children()[0].name == 'smmap'           # ... which has smmap as single submodule
IndexError: list index out of range

======================================================================
ERROR: test_base (git.test.test_remote.TestRemote)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/lib/helper.py", line 240, in remote_repo_creator
    return func(self, rw_repo, rw_remote_repo)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_remote.py", line 473, in test_base
    assert len(rw_repo.remotes.origin.fetch(prune=True)) == 1, "deleted everything but master"
  File "/Users/peterbe/dev/PYTHON/GitPython/git/remote.py", line 743, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/remote.py", line 663, in _get_fetch_info_from_stderr
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/Users/peterbe/dev/PYTHON/GitPython/git/remote.py", line 663, in <genexpr>
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/Users/peterbe/dev/PYTHON/GitPython/git/remote.py", line 261, in _from_line
    raise ValueError("Failed to parse line: %r" % line)
ValueError: Failed to parse line: '   (refs/remotes/origin/HEAD has become dangling)\n'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.remote: DEBUG: Fetch head lines do not match lines provided via progress information
length of progress lines 2 should be equal to lines in FETCH_HEAD file 1
Will ignore extra progress lines or fetch head lines.
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.cmd: DEBUG: AutoInterrupt wait stderr: b''
git.remote: DEBUG: Fetch head lines do not match lines provided via progress information
length of progress lines 2 should be equal to lines in FETCH_HEAD file 1
Will ignore extra progress lines or fetch head lines.
git.remote: DEBUG: Fetch head lines do not match lines provided via progress information
length of progress lines 2 should be equal to lines in FETCH_HEAD file 1
Will ignore extra progress lines or fetch head lines.
git.remote: DEBUG: Fetch head lines do not match lines provided via progress information
length of progress lines 2 should be equal to lines in FETCH_HEAD file 1
Will ignore extra progress lines or fetch head lines.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_rev_parse (git.test.test_repo.TestRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_repo.py", line 692, in test_rev_parse
    assert rev_parse('@{1}') != head.commit
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/fun.py", line 240, in rev_parse
    raise IndexError("Invalid revlog index: %i" % revlog_index)
IndexError: Invalid revlog index: -2
-------------------- >> begin captured stdout << ---------------------
failed on 0.1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_submodule_update (git.test.test_repo.TestRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/lib/helper.py", line 121, in repo_creator
    return func(self, rw_repo)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_repo.py", line 716, in test_submodule_update
    sm = rwrepo.create_submodule("my_new_sub", "some_path", join_path_native(self.rorepo.working_tree_dir, sm.path))
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 306, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 389, in add
    mrepo = cls._clone_repo(repo, url, path, name, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 251, in _clone_repo
    clone = git.Repo.clone_from(url, module_checkout_path, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --separate-git-dir=/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp2n_lzif5non_bare_test_submodule_update/.git/modules/my_new_sub -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp2n_lzif5non_bare_test_submodule_update/some_path' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb' does not exist
'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_work_tree_unsupported (git.test.test_repo.TestRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_repo.py", line 831, in test_work_tree_unsupported
    rw_master.git.worktree('add', worktree_path, 'master')
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 463, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 929, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 713, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git worktree add /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_work_tree_unsupportedm_48yarg/worktree_repo master' returned with exit code 128
stderr: 'fatal: invalid reference: master'

======================================================================
ERROR: test_base_rw (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/lib/helper.py", line 121, in repo_creator
    return func(self, rw_repo)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 416, in test_base_rw
    self._do_base_tests(rwrepo)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 172, in _do_base_tests
    assert sm.update() is sm
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 513, in update
    mrepo = self._clone_repo(self.repo, self.url, self.path, self.name, n=True)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 251, in _clone_repo
    clone = git.Repo.clone_from(url, module_checkout_path, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone -n --separate-git-dir=/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp464ztadcnon_bare_test_base_rw/.git/modules/gitdb -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp464ztadcnon_bare_test_base_rw/git/ext/gitdb' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb' does not exist
'
-------------------- >> begin captured stdout << ---------------------
513 0 1 DRY-RUN: Cloning url '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb' to '/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp464ztadcnon_bare_test_base_rw/git/ext/gitdb' in submodule 'gitdb'
514 0 1 DRY-RUN: Done cloning to /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/tmp464ztadcnon_bare_test_base_rw/git/ext/gitdb

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_branch_renames (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 823, in test_branch_renames
    sm_source_repo = git.Repo.clone_from(source_url, os.path.join(rw_dir, 'sm-source'), b='master')
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone -b master -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_branch_renamesevvj3iu1/sm-source' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist
'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_git_submodule_compatibility (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 724, in test_git_submodule_compatibility
    sm = parent.create_submodule('mymodules/myname', sm_path, url=self._small_repo_url())
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 306, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 389, in add
    mrepo = cls._clone_repo(repo, url, path, name, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 251, in _clone_repo
    clone = git.Repo.clone_from(url, module_checkout_path, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --separate-git-dir=/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_git_submodule_compatibilitygjtnf1gw/parent/.git/modules/mymodules/myname -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_git_submodule_compatibilitygjtnf1gw/parent/submodules/intermediate/one' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist
'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_git_submodules_and_add_sm_with_new_commit (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 666, in test_git_submodules_and_add_sm_with_new_commit
    parent.git.submodule('add', self._small_repo_url(), 'module')
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 463, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 929, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 713, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git submodule add /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap module' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist
fatal: clone of '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' into submodule path 'module' failed'

======================================================================
ERROR: test_rename (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 799, in test_rename
    sm = parent.create_submodule(sm_name, sm_name, url=self._small_repo_url())
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 306, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 389, in add
    mrepo = cls._clone_repo(repo, url, path, name, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/objects/submodule/base.py", line 251, in _clone_repo
    clone = git.Repo.clone_from(url, module_checkout_path, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 965, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/repo/base.py", line 911, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --separate-git-dir=/var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_renameyc_3jidj/parent/.git/modules/mymodules/myname -v /Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/test_renameyc_3jidj/parent/mymodules/myname' returned with exit code 128
stderr: 'fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist
'
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: AutoInterrupt wait stderr: b"fatal: repository '/Users/peterbe/dev/PYTHON/GitPython/git/ext/gitdb/gitdb/ext/smmap' does not exist\n"
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_init_repo_object (git.test.test_docs.Tutorials)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/GitPython/lib/python3.5/site-packages/gitdb/test/lib.py", line 87, in wrapper
    return func(self, path)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_docs.py", line 64, in test_init_repo_object
    assert repo.head.ref == repo.heads.master                   # head is a symbolic reference pointing to master
AssertionError

======================================================================
FAIL: test_submodules (git.test.test_repo.TestRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_repo.py", line 702, in test_submodules
    assert len(list(self.rorepo.iter_submodules())) >= 2
AssertionError

======================================================================
FAIL: test_root_module (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/lib/helper.py", line 121, in repo_creator
    return func(self, rw_repo)
  File "/Users/peterbe/dev/PYTHON/GitPython/git/test/test_submodule.py", line 444, in test_root_module
    assert len(rsmsp) >= 2          # gitdb and async [and smmap], async being a child of gitdb
AssertionError

----------------------------------------------------------------------
Ran 179 tests in 39.095s

FAILED (errors=11, failures=3)
```

**Comment by Byron** [comment]
Thanks for bringing this up.

I have updated the README to show what's needed to do that.
In short, please consult the README for how to get a full clone with submodules, then you can run `init-tests-after-clone.sh` to set yourself up.

**Comment by peterbe** [comment]
I can confirm that following those instructions does make all the tests pass. Thanks!

**Comment by Byron** [comment]
A [new release](https://pypi.python.org/pypi?name=GitPython&version=2.0.7&:action=display) was pushed to pypi.
