### ISSUE TITLE
Achive command broken on 2.1.1?

### ISSUE THREAD

**Issue by trasher** [gitpython-developers/GitPython#573]
Hello,

I have an archive command from a script that seems to work well on 2.0.5; but that no longer seems to work on 2.1.1.

Here is the traceback:
```
Traceback (most recent call last):
  File "tools/release", line 680, in <module>
    main()
  File "tools/release", line 677, in main
    _do_build(repo, buildver)
  File "tools/release", line 271, in _do_build
    repo.archive(stream, ver, prefix=plugin_name+'/', path=paths)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 952, in archive
    self.git.archive(treeish, *path, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 424, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 873, in _call_process
    return self.execute(call, **_kwargs)
  File "/usr/lib/python2.7/site-packages/git/cmd.py", line 687, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
  File "/usr/lib/python2.7/site-packages/git/exc.py", line 74, in __init__
    super(GitCommandError, self).__init__(command, status, stderr, stdout)
  File "/usr/lib/python2.7/site-packages/git/exc.py", line 54, in __init__
    self.stdout = stdout and u"\n  stdout: '%s'" % safe_decode(stdout) or ''
  File "/usr/lib/python2.7/site-packages/git/compat.py", line 74, in safe_decode
    raise TypeError('Expected bytes or text, but got %r' % (s,))
```

I can't see what have changed :( It seems that the way I call the archive command is almost the same as in your tests. I'm using python 2.7.12.

For information, the caller script:
https://github.com/pluginsGLPI/empty/blob/master/tools/release#L271

Thanks!

**Comment by trasher** [comment]
Sounds like something else was causing the bug, since it works now with same 2.1.1 release.

**Comment by Byron** [comment]
I think the issue is related to one of these very common type-hickups, which unfortunately happened during error handling. The archive command failed, and the code trying to indicate the error failed with yet another error.

Thus I believe it is a real bug, that could certainly be fixed when reproduced reliably.
