### ISSUE TITLE
OSError: cannot allocate more memory during cloning/updating a repo

### ISSUE THREAD

**Issue by meetmangukiya** [gitpython-developers/GitPython#655]
The memory usage went as high as 59% according to top

```
Traceback (most recent call last):
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/corobo/.env/lib/python3.5/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/root/corobo/answers/service.py", line 25, in <module>
    update_docs()
  File "/root/corobo/answers/service.py", line 20, in update_docs
    git.Repo(get_abs_path('coala')).remote('origin').update()
  File "/root/corobo/.env/lib/python3.5/site-packages/git/remote.py", line 622, in update
    self.repo.git.remote(scmd, self.name, **kwargs)
  File "/root/corobo/.env/lib/python3.5/site-packages/git/cmd.py", line 425, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/root/corobo/.env/lib/python3.5/site-packages/git/cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/root/corobo/.env/lib/python3.5/site-packages/git/cmd.py", line 599, in execute
    **subprocess_kwargs
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by Byron** [comment]
GitPython cannot be blamed for the system running out of resources, just because there can be various reasons for this to happen which are entirely unrelated.
