### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by iwangzhipeng** [gitpython-developers/GitPython#671]
``` shell
SHELL$ python git_repo/migrate.py 
Traceback (most recent call last):
  File "git_repo/migrate.py", line 151, in <module>
    migrate.projects()
  File "git_repo/migrate.py", line 68, in projects
    remote.set_url(new_url=project.ssh_url_to_repo).pull(branch)
  File "/Users/wangzhipeng/.virtualenvs/migrate_tools/lib/python2.7/site-packages/git/remote.py", line 772, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/Users/wangzhipeng/.virtualenvs/migrate_tools/lib/python2.7/site-packages/git/remote.py", line 639, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/Users/wangzhipeng/.virtualenvs/migrate_tools/lib/python2.7/site-packages/git/cmd.py", line 292, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin release/v1
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```
However, manual execution is not a problem.
``` shell
SHELL$ git pull -v origin release/v1
From ssh://gitlab.xxxx.com/xxx/tokyo-hot
 * branch            release/v1 -> FETCH_HEAD
 = [up to date]      release/v1 -> origin/release/v1
Already up-to-date.
```
Code snippet:
```python
repository.remote().set_url(new_url=project.target_ssh_url_to_repo)
for branch in self._branches(repository=repository):
    remote = repository.remote()
    # update repo to latest 
    remote.set_url(new_url=project.ssh_url_to_repo).pull(branch)
    repository.git.checkout(branch)
    # change remote url
    git = remote.set_url(new_url=project.target_ssh_url_to_repo)
    # push to new remote url
    git.push(all=True)
    git.push(tags=True)
```

**Comment by Byron** [comment]
Could you provide a self-contained script to reproduce this? To me it looks like a problem with authentication, which usually works in the context of a TTY/Terminal.

**Comment by Byron** [comment]
Closed due to inactivity - please feel free to comment or reopen if the interest is rekindled.
