### ISSUE TITLE
repo.git.describe fails when doing the same command in the command line works

### ISSUE THREAD

**Issue by lylecheatham** [gitpython-developers/GitPython#723]
Hey all, trying to get some git tag info using `git describe` in a script, and it is failing when the exact same invocation of `git describe` works in the command line.

Below is me trying to run my script and the ensuing traceback and then me running an identical git describe invocation and getting the correct result

```
/Users/lyle/Documents/workspace/repo>python generateVersion.py
<git.Repo "/Users/lyle/Documents/workspace/repo/.git">
<git.TagReference "refs/tags/001.005">
Traceback (most recent call last):
  File "GenerateVersion.py", line 25, in <module>
    versionString()
  File "generateVersion.py", line 17, in versionString
    val = repo.git.describe('--tags', '--dirty', '--broken', '--long', '--match="' + str(tag) + '"')
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 1010, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 821, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git describe --tags --dirty --broken --long --match="001.005"
  stderr: 'fatal: No names found, cannot describe anything.'
/Users/lyle/Documents/workspace/repo>git describe --tags --dirty --broken --long --match="001.005"
001.005-0-g58cd38a
```
Here is my python script, it is run from the repo folder.

```
import sys
import os
import pprint
import git
from git import Repo

pp = pprint.PrettyPrinter(indent=4)

def versionString():
    repo = Repo()
    assert not repo.bare
    pp.pprint(repo)
    for tag in repo.tags:
        pp.pprint(tag)
        val = repo.git.describe('--tags', '--dirty', '--broken', '--long', '--match="' + str(tag) + '"')
        pp.pprint(val)

versionString()
```

Any ideas on what's going wrong here?

EDIT:

version information:
```
/Users/lyle>pip show gitpython
Name: GitPython
Version: 2.1.8
Summary: Python Git Library
Home-page: https://github.com/gitpython-developers/GitPython
Author: Sebastian Thiel, Michael Trier
Author-email: byronimo@gmail.com, mtrier@gmail.com
License: BSD License
Location: /Library/Python/2.7/site-packages
Requires: gitdb2
```

**Comment by Byron** [comment]
Thanks for posting! I can reproduce the issue as well.
The fix is to not quote the string, so `--match="001.005"` becomes `--match=001.005`.

Reason for this is that `GitPython` does not use a shell to execute git, but calls it 'directly'. The quotes are usually processed by your shell and are not visible to `git`.
However, the python code presented here literally tries to find a tag that matches `"001.005"`, which does not exist.
