### ISSUE TITLE
Use custom ssh key cannot clone

### ISSUE THREAD

**Issue by Too-Naive** [gitpython-developers/GitPython#725]
#690 
After solve the fetch/pull error, I found that I still can not clone from remote.
```python
os.environ['GIT_SSH_COMMAND'] = 'sudo ssh -v -i /root/key'
with Git().custom_environment(GIT_SSH_COMMAND=os.environ['GIT_SSH_COMMAND']):
	repo = Repo.clone_from('git@github.com:somebody/someproject','test')
```
output:
```
DEBUG:git.cmd:Popen(['git', 'clone', '-v', 'git@github.com:somebody/someproject', 'test'], cwd=/root/test/wel, universal_newlines=True, shell=None)
DEBUG:git.repo.base:Cmd(['git', 'clone', '-v', 'git@github.com:somebody/someproject', 'test'])'s unused stdout: Initialized empty Git repository in /root/test/.git/

DEBUG:git.cmd:AutoInterrupt wait stderr: 'Permission denied (publickey).\nfatal: The remote end hung up unexpectedly\n'
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    repo = Repo.clone_from('git@github.com:somebody/someproject','test')
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 982, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 933, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python2.7/site-packages/git/util.py", line 336, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 418, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@github.com:somebody/someproject test
  stderr: 'Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

**Comment by Byron** [comment]
I would think creating a temporary instance of the `Git` command helper does not affect the `clone_from` call at all.

Instead you probably want to pass the environment directly when cloning [as described in the docs](http://gitpython.readthedocs.io/en/stable/reference.html?highlight=clone_from#git.repo.base.Repo.clone_from).

I am closing this one assuming that will work for you. But please feel free to comment if that's not the case and it might be reopened.
