### ISSUE TITLE
Diffing commit to index does not work

### ISSUE THREAD

**Issue by tomkcook** [gitpython-developers/GitPython#728]
To reproduce:

```
repo = Repo('.')
diff = repo.head.commit.diff(repo.index)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/git/diff.py", line 152, in diff
    index = diff_method(self.repo, proc)
  File "/usr/lib/python3/dist-packages/git/diff.py", line 501, in _index_from_raw_format
    handle_process_output(proc, handle_diff_line, None, finalize_process, decode_streams=False)
  File "/usr/lib/python3/dist-packages/git/cmd.py", line 119, in handle_process_output
    return finalizer(process)
  File "/usr/lib/python3/dist-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/usr/lib/python3/dist-packages/git/cmd.py", line 292, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git diff-tree 98229d5b82e2c6f698eef8e87b234738d9c4c96d <git.index.base.IndexFile object at 0x7efc19508ef8> -r --abbrev=40 --full-index -M --raw --no-color

```

**Comment by tomkcook** [comment]
Although I see `repo.head.commit.diff() does the same thing - still, it'd be nice if it handled the index correctly.
