### ISSUE TITLE
 self.pid = _posixsubprocess.fork_exec( AttributeError: 'NoneType' object has no attribute 'fork_exec'

### ISSUE THREAD

**Issue by lejiangkai** [gitpython-developers/GitPython#742]
when i use

repo = Repo('mypath')
 repo.head.reference = repo.create_head('test','HEAD~1');
 repo.head.reset(index=True, working_tree=True)

errormsg

 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1484, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'

when i in  _posixsubprocess.py file add   **import _posixsubprocess** is work 
 import _posixsubprocess
  self.pid = _posixsubprocess.fork_exec(
                            args, executable_list,
                            close_fds, sorted(fds_to_keep), cwd, env_list,
                            p2cread, p2cwrite, c2pread, c2pwrite,
                            errread, errwrite,
                            errpipe_read, errpipe_write,
                            restore_signals, start_new_session, preexec_fn)

**Comment by Byron** [comment]
It seems to be a problem in the python installation, as subprocess spawning fails because the respective object is not initialized. I have no idea why that would be the case though.
You could try to use `Popen` yourself to see if subprocesses can be spawned at all on this system.
Unless there are additional comments indicating that this is indeed an issue with `GitPython`, I don’t think this is something we can fix.
Thanks for your understanding, please feel free to provide more infromation that would help reproduce the issue though.

**Comment by matusnovak** [comment]
I have this exact same problem. I have tried running it on my local machine, via Docker, or even on Amazon EC2, I always get this error.

It happens when I try to initialize a repository `git.Repo.init('/some/dir/name')`

I have tried Python 3.8 and 3.9 but receive the same error.

Stack trace:

```
  File "/home/mnovak/.local/lib/python3.9/site-packages/git/repo/base.py", line 937, in init
    git.init(**kwargs)
  File "/home/mnovak/.local/lib/python3.9/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/mnovak/.local/lib/python3.9/site-packages/git/cmd.py", line 1006, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/mnovak/.local/lib/python3.9/site-packages/git/cmd.py", line 721, in execute
    proc = Popen(command,
  File "/usr/lib/python3.9/subprocess.py", line 946, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1751, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'
```

GitPython version: 3.1.12

What is interesting is that when `subprocess.py` is imported, the `_posixsubprocess` is initialised just fine, it points to a real builtin module. When `git.Repo.init()` is executed, somehow that `subprocess.py` is re-imported with `_posixsubprocess` and initialised to `None`.

**Comment by Byron** [comment]
I have also seen standard modules magically disappearing when python is shutting down - maybe that's related here as well.

**Comment by edisonwong520** [comment]
i have the same issue .it's sucks  and spend my too much in troubleshooting . a big project using in python is totally bad and sucks

**Comment by edisonwong520** [comment]
`
def main():
    try:
        repo = Repo("/data/apps/stree/falconcfg")
        # repo = Repo("/data/apps/stree/falconcfg")
        print("repo info {}".format(repo))
        print("repo info git {}".format(repo.git))
        print("repo info git log {}".format(repo.git.log()))
    except Exception as e:
        print("err {}".format(e))`

it works in as test.py,but in my project,the same code and it doesn't work!
[2021-08-30 17:37:06 +0800] [10065] [INFO] repo info <git.Repo "/data/apps/stree/falconcfg/.git">
[2021-08-30 17:37:06 +0800] [10065] [INFO] repo info git <git.cmd.Git object at 0x7f377e40bdc8>
[2021-08-30 17:37:06 +0800] [10065] [ERROR] trace Traceback (most recent call last):
  File "/data/apps/stree/services/config.py", line 60, in git_pull
    app.logger.info("repo info git log {}".format(repo.git.log()))
  File "/data/apps/stree/py36/lib64/python3.6/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/data/apps/stree/py36/lib64/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/data/apps/stree/py36/lib64/python3.6/site-packages/git/cmd.py", line 735, in execute
    **subprocess_kwargs
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1288, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
AttributeError: 'NoneType' object has no attribute 'fork_exec'`
`
