### ISSUE TITLE
Failed to initialize repository while the path contains "~"

### ISSUE THREAD

**Issue by tonyseek** [gitpython-developers/GitPython#83]
I have tried to initialize a repository using a short path which contains "~", a exception be raised:

```
>>> repo = git.Repo.init("~/test.git", bare=True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python2.7/site-packages/git/repo/base.py", line 657, in init
    return Repo(path)
  File ".../lib/python2.7/site-packages/git/repo/base.py", line 98, in __init__
    raise NoSuchPathError(epath)
NoSuchPathError: /home/username/test.git
```

If I create the target directory first, it will be another exception:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python2.7/site-packages/git/repo/base.py", line 657, in init
    return Repo(path)
  File ".../lib/python2.7/site-packages/git/repo/base.py", line 122, in __init__
    raise InvalidGitRepositoryError(epath)
InvalidGitRepositoryError: /home/username/test.git
```

But while I use the full path without any character `~` instead of, it works.

```
>>> repo = git.Repo.init("/home/username/test.git", bare=True)
>>> repo
<git.Repo "/home/username/test.git">
>>> 
```

**Comment by Byron** [comment]
This issue is fixed, and verified by [a new test-case](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_repo.py#L387).

Also there is a [video on youtube](http://youtu.be/Pw1KJ-E3ii8) showing the process of fixing the issue.
