### ISSUE TITLE
fails to import in windows 10 

### ISSUE THREAD

**Issue by Josverl** [gitpython-developers/GitPython#970]
just want to let you know that the module just throws errors in importing and a newly installed windows 10 & python box 😢 

```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from git import Repo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\git\__init__.py", line 40, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\git\config.py", line 26, in <module>
    from git.util import LockFile
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\site-packages\git\util.py", line 17, in <module>
    from unittest import SkipTest
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\unittest\__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\unittest\async_case.py", line 4, in <module>
    from .case import TestCase
  File "C:\Users\josverl\AppData\Local\Programs\Python\Python38-32\lib\unittest\case.py", line 302, in <module>
    class _CapturingHandler(logging.Handler):
AttributeError: module 'logging' has no attribute 'Handler'
```

**Comment by Byron** [comment]
I am sorry for your trouble.

Unfortunately, with the information provided, I don't think it's possible to reproduce the issue.
Maybe you want to try again with the latest release, v3.0.7 .

The issue will be closed due to low likelihood of a fix, and I invite you to leave a comment if you managed to solve it so others can benefit. Thank you

**Comment by Harmon758** [comment]
[`logging.Handler`](https://docs.python.org/3/library/logging.html#logging.Handler) is part of the standard library.
Make sure you don't have another file/module named `logging` in your path.
