### ISSUE TITLE
`git.Repo.index.add` fails on Python 3.6.7 installed via `conda` on MacOS

### ISSUE THREAD

**Issue by joseph-zhong** [gitpython-developers/GitPython#977]
I've tried running on two MacOS laptops, both installing various version of `GitPython` (2.0.8, 2.1.13, 3.0.5) and reach an error while trying to perform a `Repo.index.add` operation.
I'm running git version `2.x.x` on each device.

```bash
$ git --version
git version 2.13.5
```

```python
>>> repo = git.Repo('/Users/josephz/work/src')
>>> repo
<git.Repo "/Users/josephz/work/src/.git">
>>> diffs = repo.head.commit.diff(None)
>>> type(diffs)
<class 'git.diff.DiffIndex'>
>>> repo.index.add([d.a_path for d in diffs])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    repo.index.add(diffs)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/base.py", line 798, in add
    self.write(ignore_extension_data=not write_extension_data)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/base.py", line 202, in write
    self.entries
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/base.py", line 132, in _set_cache_
    self._deserialize(stream)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/base.py", line 161, in _deserialize
    self.version, self.entries, self._extension_data, _conten_sha = read_cache(stream)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/fun.py", line 187, in read_cache
    version, num_entries = read_header(stream)
  File "/Users/josephz/miniconda3/envs/dev/lib/python3.6/site-packages/git/index/fun.py", line 167, in read_header
    assert version in (1, 2)
```

Several months ago I was able to use GitPython just fine so I'm not sure what has changed since.
Thanks!

**Comment by joseph-zhong** [comment]
Actually as I'm checking now, it appears that `repo.index.add` fails with this error even if I pass it an empty list:

```python
>>> repo.index.add([])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    repo.index.add([])
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/base.py", line 798, in add
    self.write(ignore_extension_data=not write_extension_data)
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/base.py", line 202, in write
    self.entries
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/base.py", line 132, in _set_cache_
    self._deserialize(stream)
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/base.py", line 161, in _deserialize
    self.version, self.entries, self._extension_data, _conten_sha = read_cache(stream)
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/fun.py", line 187, in read_cache
    version, num_entries = read_header(stream)
  File "/Users/josephz/miniconda3/envs/ctrldev/lib/python3.6/site-packages/git/index/fun.py", line 167, in read_header
    assert version in (1, 2)
AssertionError
```

**Comment by joseph-zhong** [comment]
Any update on this? 
I can't seem to replicate this issue from an Pypi installation, so I wonder if there's anything different about the package from conda?

**Comment by Byron** [comment]
It looks like whatever happens, the Git version uses a new index version. The assertion fails because it's neither 1 or 2. The problem is that GitPython tries to parse the git index file, but can't as the version is too advanced.

This would require GitPython to catchup with git, and PRs are very welcome of course. In the meantime, it might be easiest to use older git versions, if possible.

**Comment by joseph-zhong** [comment]
@Byron 
Thanks for the response. 
I don't think I'm quite understanding, are you saying that the installed Git version itself is too far advanced? In a different, much smaller repository (without GitLFS) I was able to run the above without any issues. Do you know what else the assertion might be referring to?
Thanks!

**Comment by Byron** [comment]
Yes, that's what I am thinking. The index version is neither 1 or 2, which are the only ones GitPython can handle itself.

As a workaround, you can probably use `repo.git.add(…)` while using [this as reference](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

**Comment by joseph-zhong** [comment]
hm, I'm actually not sure it's referring to the locally installed git version; after cleanly cloning the repository the error resolved has seemed to resolve itself. If I run into this again I'll open the issue once more.
