### ISSUE TITLE
Can't push to git: -> use https:

### ISSUE THREAD

**Issue by Zethson** [gitpython-developers/GitPython#992]
Dear developers,

```
import click
from github import Github
from git import Repo


@click.command()
@click.option('--github_username',  prompt='github username')
@click.option('--github_password',  prompt='github_password', hide_input=True)
@click.option('--github_email',  prompt='github_email')
def run(github_username, github_password, github_email):
    # login to github
    authenticated_github_user = Github(github_username, github_password)
    user = authenticated_github_user.get_user()

    is_org: bool = False
    # create the new repository
    if is_org:
        org = authenticated_github_user.get_organization('someorg')
        repo = org.create_repo('projectname', description='somedescription')
    else:
        repo = user.create_repo('testrepo_github_api', description='this is a test')

    # clone the repository
    repoClone = pygit2.clone_repository(repo.git_url, '/tmp/test_clone')

    # copy files into the repository if they should also be committed and pushed
    with open('/tmp/test_clone/test.txt', 'w') as f:
        f.write('wtf')


    repo_dir = '/tmp/test_clone'
    repo = Repo(repo_dir)
    file_list = [
        'test.txt'
    ]
    commit_message = 'test'
    repo.index.add(file_list)
    repo.index.commit(commit_message)
    origin = repo.remote('origin')
    origin.push()


if __name__ == '__main__':
    run()

```

This unfortunately results in:

```
Traceback (most recent call last):
  File "/home/zeth/PycharmProjects/cookietemple/cookietemple/create/github_support.py", line 45, in <module>
    run()
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/zeth/PycharmProjects/cookietemple/cookietemple/create/github_support.py", line 41, in run
    origin.push()
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/git/remote.py", line 846, in push
    return self._get_push_info(proc, progress)
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/git/remote.py", line 732, in _get_push_info
    proc.wait(stderr=stderr_text)
  File "/home/zeth/lukas_heumos_website/lib/python3.8/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push --porcelain origin
  stderr: 'fatal: remote error:
  You can't push to git://github.com/Zethson/testrepo_github_api.git
  Use https://github.com/Zethson/testrepo_github_api.git'
```

**Comment by Byron** [comment]
Unfortunately this issue doesn't make clear what the author thinks GitPython should do to alleviate the problem. By the looks of it, git itself is unable to push to github using the 'git' protocol, so GitHub suggests using https. SSH would certainly work as well.

Even though I am closing the issue for the aforementioned reason, please feel free to comment for clarification or follow-up questions.
